# Generated by Django 2.0 on 2018-04-09 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Fiche_Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('prix', models.IntegerField(max_length=10)),
                ('description', models.TextField(default='DESC', max_length=200)),
                ('types', models.CharField(default='Pharmacie', max_length=10)),
                ('stock', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.ImageField(blank=True, default='pharmacie.jpg', upload_to='')),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.IntegerField(max_length=9)),
                ('horaire', models.CharField(max_length=50)),
                ('partenaire', models.BooleanField(default='1')),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fiche_produit',
            name='nom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Pharmacie'),
        ),
    ]
