# Generated by Django 2.0 on 2018-03-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commandes_Effectuees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPatient', models.CharField(max_length=30)),
                ('prenomPatient', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('telephonePatient', models.IntegerField(max_length=9)),
                ('commande', models.CharField(max_length=200)),
                ('dateCommande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('dateLivraison', models.DateTimeField(auto_now_add=True, verbose_name='Date de livrason')),
                ('livree', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Fiche_Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('prix', models.IntegerField(max_length=10)),
                ('description', models.TextField(default='DESC', max_length=200)),
                ('types', models.CharField(default='Pharmacie', max_length=10)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('profil', models.ImageField(blank=True, default='pharmacie.jpg', upload_to='')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.IntegerField(max_length=9)),
                ('horaire', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='fiche_produit',
            name='nom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Pharmacie'),
        ),
    ]
