# Generated by Django 2.0 on 2018-04-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes_effectuees',
            name='payer',
            field=models.CharField(max_length=30),
        ),
    ]
