# Generated by Django 2.0 on 2018-04-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_auto_20180412_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes_effectuees',
            name='payer',
            field=models.CharField(choices=[('Wari', 'Wari'), ('Orange Money', 'Orange Money'), ('Carte de credit', 'Carte de credit')], max_length=100),
        ),
    ]
