# Generated by Django 2.0 on 2018-04-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_commandes_effectuees'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes_effectuees',
            name='payer',
            field=models.BooleanField(default=False),
        ),
    ]
