# Generated by Django 2.0 on 2018-04-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0003_pharmacie_partenaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacie',
            old_name='pharmacie',
            new_name='user',
        ),
    ]
