# Generated by Django 2.0 on 2018-04-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0003_commandes_effectuees_payer'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(max_length=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Commandes_Effectuees')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Fiche_Produit')),
            ],
        ),
    ]
