# Generated by Django 2.0 on 2018-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_detail_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes_effectuees',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
