# Generated by Django 2.0 on 2018-04-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0005_commandes_effectuees_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes_effectuees',
            name='commande',
        ),
    ]
