# Generated by Django 2.0 on 2018-04-09 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_femme'),
        ('pharmacie', '0007_commandes_effectuees_ordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes_effectuees',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
            preserve_default=False,
        ),
    ]
