# Generated by Django 2.0 on 2018-04-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0008_commandes_effectuees_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_commande',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
