# Generated by Django 2.0 on 2018-04-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0009_detail_commande_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes_effectuees',
            name='Pharmacie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Pharmacie'),
            preserve_default=False,
        ),
    ]
