# Generated by Django 2.0 on 2018-04-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0010_commandes_effectuees_pharmacie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes_effectuees',
            name='Pharmacie',
        ),
    ]
