# Generated by Django 2.0.3 on 2018-04-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0009_femme'),
        ('pharmacie', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(max_length=1)),
                ('dateNaissance', models.DateField(blank=True)),
                ('telephone', models.IntegerField(max_length=9)),
                ('adresse', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsLivreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacie', models.CharField(max_length=50)),
                ('nomPatient', models.CharField(max_length=30)),
                ('prenomPatient', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('telephonePatient', models.IntegerField(max_length=9)),
                ('dateCommande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('dateLivraison', models.DateTimeField(auto_now_add=True, verbose_name='Date de livrason')),
                ('lu', models.BooleanField(default=False)),
                ('livree', models.BooleanField(default=False)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Commandes_Effectuees')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livreur.Livreur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneDeLivraison', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='livreur',
            name='zoneDeLivraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livreur.Region'),
        ),
    ]
