# Generated by Django 2.0 on 2018-04-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationsLivreur',
        ),
    ]
