# Generated by Django 2.0 on 2018-04-09 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_femme'),
        ('livreur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsLivreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacie', models.CharField(max_length=50)),
                ('nomPatient', models.CharField(max_length=30)),
                ('prenomPatient', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('telephonePatient', models.IntegerField(max_length=9)),
                ('commande', models.CharField(max_length=200)),
                ('dateCommande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('dateLivraison', models.DateTimeField(auto_now_add=True, verbose_name='Date de livrason')),
                ('lu', models.BooleanField(default=False)),
                ('livree', models.BooleanField(default=False)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livreur.Livreur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
