# Generated by Django 2.0.3 on 2018-04-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0002_delete_notificationslivreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsLivreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacie', models.CharField(max_length=50)),
                ('nomPatient', models.CharField(max_length=30)),
                ('prenomPatient', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('telephonePatient', models.IntegerField(max_length=9)),
                ('commande', models.CharField(max_length=200)),
                ('dateCommande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('dateLivraison', models.DateTimeField(auto_now_add=True, verbose_name='Date de livrason')),
                ('lu', models.BooleanField(default=False)),
            ],
        ),
    ]
