# Generated by Django 2.0 on 2018-04-09 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0002_notificationslivreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationslivreur',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.Commandes_Effectuees'),
        ),
    ]
