# Generated by Django 2.0.3 on 2018-04-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0003_notificationslivreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationslivreur',
            name='livreur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livreur.Livreur'),
            preserve_default=False,
        ),
    ]
