# Generated by Django 2.0 on 2018-03-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('nom', models.CharField(max_length=30, null=True)),
                ('prenom', models.CharField(max_length=30, null=True)),
                ('sexe', models.CharField(max_length=30, null=True)),
                ('allergie', models.CharField(max_length=100, null=True)),
                ('traitement', models.CharField(max_length=100, null=True)),
                ('dateNaissance', models.DateTimeField(auto_now_add=True, verbose_name='Date de naissance')),
            ],
        ),
    ]
