# Generated by Django 2.0 on 2018-03-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('medicaments', models.CharField(max_length=255)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecin.Medecin')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='login',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prenom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='traitement',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='ordonnances',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
    ]
