# Generated by Django 2.0 on 2018-04-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
