# Generated by Django 2.0 on 2018-03-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
