# Generated by Django 2.0 on 2018-04-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnances',
            name='medicaments',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
