# Generated by Django 2.0 on 2018-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20180401_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dateNaissance',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
