# Generated by Django 2.0 on 2018-04-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20180401_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbi',
            name='user',
        ),
        migrations.DeleteModel(
            name='userbi',
        ),
    ]
