# Generated by Django 2.0 on 2018-04-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20180402_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnances',
            name='dateSoumission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
