# Generated by Django 2.0 on 2018-04-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_ordonnances_datesoumission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnances',
            name='medecin',
        ),
    ]
