# Generated by Django 2.0 on 2018-04-03 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
        ('patient', '0006_remove_ordonnances_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnances',
            name='medecin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medecin.Medecin'),
            preserve_default=False,
        ),
    ]
