# Generated by Django 2.0 on 2018-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0002_auto_20180401_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_userbi',
            field=models.BooleanField(default=False),
        ),
    ]
