# Generated by Django 2.0 on 2018-04-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_auto_20180331_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='slug',
        ),
    ]
