# Generated by Django 2.0 on 2018-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0003_remove_medecin_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
