# Generated by Django 2.0.3 on 2018-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0005_auto_20180402_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='nom',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
